services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER_LOWERCASE}/${PROJECT_NAME_LOWERCASE}:latest
    container_name: background-tube
    restart: unless-stopped
    labels:
      pi.ui.primary: "true"
    ports:
      - "127.0.0.1:18080:8080"
    environment:
      PORT: "8080"
      NODE_ENV: "production"
      YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
      YOUTUBE_REGION: "${YOUTUBE_REGION}"